---
booktitle: Proceedings of the Tenth European Workshop on Reinforcement Learning
logoright: ewrl_logo.jpg
publisher: PMLR
volume: 24
year: '2012'
month: 6
start: 2012-06-30
end: 2012-07-01
published: 2013-01-12
shortname: EWRL 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: DeisenrothEWRL2012
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: false
editor:
- given: Marc Peter
  family: Deisenroth
- given: Csaba
  family: Szepesvári
- given: Jan
  family: Peters
description: |
  Proceedings of the Tenth European Workshop on Reinforcement Learning
    Held in Edinburgh, Scotland on 30 June to 01 July 2012

  Published as Volume 24 by the Proceedings of Machine Learning Research on 12 January 2013.

  Volume Edited by:
    Marc Peter Deisenroth
    Csaba Szepesvári
    Jan Peters

  Series Editors:
    Neil D. Lawrence
date_str: 30 Jun--01 Jul
url: http://proceedings.mlr.press
baseurl: "/v24"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v24
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: European Workshop on Reinforcement Learning
  url: 
  location: Edinburgh, Scotland
  dates:
  - 2012-06-30
  - 2012-07-01
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v24.bib
