---
booktitle: Proceedings of the Tenth European Workshop on Reinforcement Learning
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
logo: ewrl_logo.jpg
publisher: PMLR
volume: 24
year: '2012'
month: 6
start: 2012-06-30
end: 2012-07-01
published: 2013-01-12
shortname: EWRL 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: DeisenrothEWRL2012
cycles: false
editor:
- given: Marc Peter
  family: Deisenroth
- given: Csaba
  family: Szepesvári
- given: Jan
  family: Peters
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Tenth European Workshop on Reinforcement Learning
    Held in Edinburgh, Scotland on 30 June to 01 July 2012

  Published as Volume 24 by the Proceedings of Machine Learning Research on 12 January 2013.

  Volume Edited by:
    Marc Peter Deisenroth
    Csaba Szepesvári
    Jan Peters

  Series Editors:
    Neil D. Lawrence
date_str: 30 Jun--01 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v24"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v24
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: European Workshop on Reinforcement Learning
  url: 
  location: Edinburgh, Scotland
  dates:
  - 2012-06-30
  - 2012-07-01
  number: 10
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
